"""empty message

Revision ID: f6a376ea1289
Revises: b77295c434e1
Create Date: 2016-05-04 09:47:32.737000

"""

# revision identifiers, used by Alembic.
revision = 'f6a376ea1289'
down_revision = 'b77295c434e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=128), nullable=True),
    sa.Column('session_URL', sa.String(length=128), nullable=True),
    sa.Column('program_lang', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_name'), 'sessions', ['session_name'], unique=True)
    op.create_table('registrations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_index(op.f('ix_sessions_session_name'), table_name='sessions')
    op.drop_table('sessions')
    ### end Alembic commands ###
